service: optimize

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  optimize:
    handler: src/optimize.handle
    environment:
      bucket: apiimagens
    events:
      - s3:
          bucket: apiimagens
          event: s3:ObjectCreated:*
          rules:
            - prefix: updados/
            - suffix: .jpg
      - s3:
          bucket: apiimagens
          event: s3:ObjectCreated:*
          rules:
            - prefix: updados/
            - suffix: .png